<a href="https://colab.research.google.com/github/Aditya-11/Reinforcement-learning-Experiments/blob/master/frozen_lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# used by the OpenAI environment to train the agent
# Made by Aditya Dubey

import numpy as np
!pip install gym

In [0]:
import gym
import random 

Frozen lake implementation by using Q learning , agent has to travel from start to end and reach the end destination.

The map of the game looks something like this , agent has to start from s and can end the game either reaching goal or falling in the hole. Agent can only walk on the frozen paths

![alt text](https://analyticsindiamag.com/wp-content/uploads/2018/03/Frozen-Lake.png)   ![alt text](https://analyticsindiamag.com/wp-content/uploads/2018/03/description.png)






In [0]:
# using open AI gym implementation
env = gym.make("FrozenLake-v0")

In [0]:
# now we will calculate action and state size of the environment

action_size = env.action_space.n #columns
state_size = env.observation_space.n # rows

q_table = np.zeros((state_size,action_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
# create hyper parameters for the learning algorithm 

total_episodes = 25000        # Total episodes
learning_rate = 0.9           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.0055            # Exponential decay rate for exploration prob


# Q learning algrithm to be implemented


![alt text](https://raw.githubusercontent.com/simoninithomas/Deep_reinforcement_learning_Course/1ee37cfc3130057f828f19b3cee6066d41c1eeb4/Q%20learning/FrozenLake/qtable_algo.png)


In [0]:
# Q learning algorithm to be implemented , Bellman equation to update the Q table value

rewards = []

for episode in range(total_episodes):
  # reset the env
  state = env.reset()
  step = 0
  done = False
  total_rewards = 0

  for step in range(max_steps):
    # choose an action a in the current world

    e_tradeoff = random.uniform(0,1)

    """
    if e_tradeoff > epsilon :
      Exploitation mode -> Use Q table to choose the action 
    else : 
      Exploration mode -> choose a random action 
    """

    if (e_tradeoff > epsilon) :
      action = np.argmax(q_table[state,:])
    else :
      action = env.action_space.sample()

    # take action a and go to state s' and reward r

    new_state,reward,done,info = env.step(action)

    # implementing the belman equation 
    q_table[state,action] = q_table[state,action] +  learning_rate * (reward + gamma * np.max(q_table[new_state,:]) - q_table[state,action])

    total_rewards += reward

    state = new_state

    # if we finish the episode

    if done == True : 
      break

  
  # update the epsilon value (exploration vs exploitation value)
  epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
  rewards.append(total_rewards)


print("Score over the time : ",(sum(rewards)/int(total_episodes)))

print(q_table)


Score over the time : % 0.4570625
[[1.50140905e-01 9.00963537e-03 1.13636676e-02 1.50717827e-02]
 [7.84611517e-04 2.86960773e-03 5.85236242e-03 1.44002062e-01]
 [2.87594883e-03 3.85480153e-03 3.59224704e-02 5.35481182e-03]
 [3.76257363e-03 5.23720359e-03 1.63803104e-04 9.16885860e-03]
 [2.95854800e-01 2.67329729e-02 1.62931593e-02 3.17779411e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.68108893e-06 5.73440649e-08 6.09739135e-03 1.28955435e-07]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.80813885e-04 5.62046869e-03 2.05348039e-03 3.78612361e-01]
 [6.37456429e-04 1.29850151e-01 2.23640710e-03 5.59741789e-03]
 [4.97134720e-01 3.32246978e-03 1.08175324e-03 1.93042151e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.88701509e-02 1.97962628e-01 3.11010958e-01 8.05291834e-02]
 [1.20238148e-01 9.56906356e-01 1.14637739e-01 9.94023805e-02]
 [0.00000000e+00 0.00

In [0]:
env.reset()

for episode in range(10):
  state = env.reset()
  step = 0
  done = False
  print("EPISODE % *****************************************************",episode)

  for step in range(max_steps):
    action = np.argmax(q_table[state,:])
    new_state , reward , done , info = env.step(action)

    if done:
      # print the last state whether the agent has reahed the goal or pithole
      env.render() 
      print("Number of Steps ",step)
      break
  state = new_state
env.close()

EPISODE % ***************************************************** 0
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 24
EPISODE % ***************************************************** 1
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 11
EPISODE % ***************************************************** 2
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 23
EPISODE % ***************************************************** 3
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 6
EPISODE % ***************************************************** 4
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 10
EPISODE % ***************************************************** 5
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 15
EPISODE % ***************************************************** 6
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 3
EPISODE % ***************************************************** 7
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 8
EPISODE % ***************************************************** 8
  (Left)


In [0]:
# Q learning algorithm to be implemented , Bellman equation to update the Q table value
# training the Q table differently , lets not choose exploration / exploitation randomly and keep a threshold

rewards = []

for episode in range(total_episodes):
  # reset the env
  state = env.reset()
  step = 0
  done = False
  total_rewards = 0

  for step in range(max_steps):
    # choose an action a in the current world

    #e_tradeoff = random.uniform(0,1)

    """
    if e_tradeoff > epsilon :
      Exploitation mode -> Use Q table to choose the action 
    else : 
      Exploration mode -> choose a random action 
    """

    if (epsilon>0.59) :
      action = np.argmax(q_table[state,:])
    else :
      action = env.action_space.sample()

    # take action a and go to state s' and reward r

    new_state,reward,done,info = env.step(action)

    # implementing the belman equation 
    q_table[state,action] = q_table[state,action] +  learning_rate * (reward + gamma * np.max(q_table[new_state,:]) - q_table[state,action])

    total_rewards += reward

    state = new_state

    # if we finish the episode

    if done == True : 
      break

  
  # update the epsilon value (exploration vs exploitation value)
  epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
  rewards.append(total_rewards)


print("Score over the time : ",(sum(rewards)/int(total_episodes)))

print(q_table)

Score over the time : % 0.0158125
[[6.63215779e-01 7.18280218e-01 7.30380770e-01 7.17983046e-01]
 [6.83328699e-01 6.76742088e-01 7.59177790e-01 7.52128087e-01]
 [7.21332006e-01 7.66943613e-01 7.63085280e-01 7.53879717e-01]
 [7.41052946e-04 6.56181904e-01 6.04659262e-01 5.89370803e-01]
 [7.70167545e-01 6.93771102e-01 6.91297178e-01 6.29056998e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.40560754e-01 8.51010639e-03 8.07873274e-01 6.46948598e-07]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.23186065e-02 8.11427307e-01 7.14526513e-01 7.23431662e-01]
 [8.09720572e-01 7.79233834e-01 8.14918756e-01 8.58738695e-01]
 [8.13263780e-01 8.58158053e-01 7.64397824e-01 7.41585770e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.15463166e-01 8.15561687e-01 8.57785965e-01 7.35071860e-02]
 [8.62910956e-01 8.14377401e-01 8.24433588e-01 8.55405452e-01]
 [0.00000000e+00 0.00

In [0]:
# Lets play the game using the Q_table which we trained

env.reset()

for episode in range(10):
  state = env.reset()
  step = 0
  done = False
  print("EPISODE % *****************************************************",episode)

  for step in range(max_steps):
    action = np.argmax(q_table[state,:])
    new_state , reward , done , info = env.step(action)

    if done:
      # print the last state whether the agent has reahed the goal or pithole
      env.render() 
      print("Number of Steps %",step)
      break
  state = new_state
env.close()

EPISODE % ***************************************************** 0
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 2
EPISODE % ***************************************************** 1
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 2
EPISODE % ***************************************************** 2
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 4
EPISODE % ***************************************************** 3
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 11
EPISODE % ***************************************************** 4
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 8
EPISODE % ***************************************************** 5
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 6
EPISODE % ***************************************************** 6
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 3
EPISODE % ***************************************************** 7
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of Steps % 8
EPISODE % ***************************************************** 8
  (Ri